name: Symfony CI YAML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write  # Required for the Docker Build and Push action

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.11'  # Adjust if necessary
          extensions: mbstring, mysqli, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
          export DOCKER_COMPOSE_VERSION
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify Docker Compose installation

      - name: Build Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mohammed3mg/symfony_blogpost
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.override.yaml up -d

      - name: Create Database Schema
        run: |
          docker-compose exec -T app bin/console doctrine:schema:create

      - name: Run PHPUnit Tests
        run: |
          docker-compose exec -T app ./vendor/bin/phpunit --testdox --coverage-text

      - name: Tear Down Docker Compose
        run: |
          docker-compose down
